name: ci

on:
  push:
    branches:
      - main
      - beta-pre-release
      - beta-monorepo
  pull_request:
    branches:
      - main
      - beta-pre-release
      - beta-monorepo
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - uses: codecov/codecov-action@v3
